### ISSUE TITLE
Docs UPdate

### ISSUE THREAD

**Issue by pedromorgan** [collective/icalendar#102]
I notice that Sphinx is not automatically creating the API docs ?

Is anyone working on this or shall I fix it ?

Pete

**Comment by OptiverTimAll** [comment]
It looks like the current version of the docs includes automatic API docs, but while the library is up to v3.8.4, the online docs are stuck at version "3.0dev". If somebody could upload the latest version of the docs, that would be much appreciated.

**Comment by untitaker** [comment]
The RTD builds fail. I supposedly fixed them in https://github.com/collective/icalendar/commit/06c700adf516de14e82a1add58df6c3917c3c292.

**Comment by YPCrumble** [comment]
Thanks all for the great repo!

This still appears to be an issue - docs currently still show the `python setup.py install` instructions vs. `pip install icalendar` in the GitHub repo.

I'm happy to lend a hand here but I suspect someone with access to the RTD account would need to look into why the automatic build is still failing?
