### ISSUE TITLE
How to add 'X-APPLE-STRUCTURED-LOCATION'

### ISSUE THREAD

**Issue by joshhunt** [collective/icalendar#116]
I'm looking to embed the new X-APPLE-STRUCTURED-LOCATION used in Mavericks to specify a rich location into .ics files.

Calendar in Mavericks builds it like this:

```
[...]
DTSTART:20131104T070000
CREATED:20131119T222157Z
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-ADDRESS=367 George     Street\\nSydn
 ey CBD NSW 2000;X-APPLE-RADIUS=72;X-TITLE=367 George Street:geo:-33.8689
 97,151.206775
END:VEVENT
```

How can I add this into an Event object? I'm able to form the string myself, but I'm unsure how to add this into the Event object, of if it's even the right way to do it.

**Comment by grosch** [comment]
Note that if you also have a LOCATION element that it must match exactly the location you specify in the X-APPLE-STRUCTURED-LOCATION.  If it differs, iCal won't display the location in a map.

**Comment by timgentry** [comment]
The following worked for me, it's basically a 'geo' URI with additional properties
```
event.x_apple_structured_location = Icalendar::Values::Uri.new(
  "geo:-33.868900,151.207000",
  "X-ADDRESS": "367 George Street Sydney CBD NSW 2000",
  "X-APPLE-RADIUS": "72",
  "X-TITLE": "367 George Street"
)
```
