### ISSUE TITLE
Some bugs from old mailing list not addressed

### ISSUE THREAD

**Issue by sappjw** [collective/icalendar#12]
I've collected some patches sent to the mailing list since 2.1 was released.  They're in http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/dev-python/icalendar/files/2.1_p20100409/ (only 01 through 04 seem to still apply).

For reference, see:

http://codespeak.net/pipermail/icalendar-dev/2009-March/000138.html
http://codespeak.net/pipermail/icalendar-dev/2009-July/000139.html
http://codespeak.net/pipermail/icalendar-dev/2010-January/000150.html
http://codespeak.net/pipermail/icalendar-dev/2010-March/000151.html (reported multiple times)

**Comment by niccokunzmann** [comment]
The links do not work any more. I close this issue. Feel free to track things down and comment!
