### ISSUE TITLE
Hint for exporting to Google Calendar

### ISSUE THREAD

**Issue by rrthomas** [collective/icalendar#121]
I just used Python icalendar to write a script to turn information from a custom calendaring sytem into an iCal file I could import into Google Calendar. It worked fine, but there was one wrinkle; I wonder whether it might be worth documenting since Google Calendar is presumably a fairly popular target:

I found that my VEVENTS needed a UID field, or Google Calendar gave an error. (To be precise, this was only a problem when I had more than one event, which is annoying in itself, as it made the problem harder to debug.)

This is not in RFC2445, of course, where the UID field is optional.

If you're interested and tell me where you'd like it I'd be happy to write a sentence for inclusion in the documentation.

**Comment by lxsli** [comment]
@rrthomas have you shared your script anywhere please? I'm using https://github.com/lxsli/add-vcal-to-google . The lack of TZ support is frustrating me (now DST has started) and if you've already cracked that nut I'd love to steal your code.

**Comment by rrthomas** [comment]
@lxsli, sorry, I would need permission to share my code; but I didn't have any problems with TZs, so I can tell you what I did: I simply hard-wired it, like this:

    s['start'] = parse_time(s['start']).replace(tzinfo=timezone("Europe/London"))

This is possible for me because the calendaring system I'm working with is London-based, and includes only events happening in London, therefore the TZ is always the same; however, it does suggest that simply setting the TZ works.

**Comment by geier** [comment]
@lxsli  you might want to have a look how we [do it in khal at the moment](https://github.com/geier/khal/blob/64d70e3eb59570cfd3af2e10dbbcf0a26bf89111/khal/khalendar/event.py#L287), as long as you have no infinitely recurring events it seems to work well enough.

**Comment by lxsli** [comment]
@rrthomas @geier thank you both for the responses! It turns out that upgrading to icalendar 3.9.0 has been a drop-in fix for me. I now get a correctly timezoned date from isoformat().

**Comment by Lx** [comment]
I guess Google Calendar's implementation may have changed since the last comment on this issue, but as of now, I can successfully import events without `UID`s.
