### ISSUE TITLE
Remove an event

### ISSUE THREAD

**Issue by Fsero** [collective/icalendar#125]
Hi there,

i'm using icalendar for parse some ics and manipulate some events, looking in the API i did not see a proper method to remove an event, i could clone the old calendar and then insert the non removed events but it's an awful way to do it.

is there another method that i could use?

Thanks in advance.

**Comment by EtienneM** [comment]
Hi!

I am also looking for a method to delete events from a calendar. Any new possibility with the newer version? Or any tips to do so?

**Comment by untitaker** [comment]
You have the `subcomponents` list on each component which you can just modify.

**Comment by EtienneM** [comment]
Thanks!

For those who wonder how it works, here is a minimal working example:

  vcalendar.subcomponents[:] = [comp for comp in vcalendar.subcomponents if my_comps(comp)]

with `my_comps` a function that return true depending on some condition on the component `comp`
