### ISSUE TITLE
Offsets larger than 24h?

### ISSUE THREAD

**Issue by untitaker** [collective/icalendar#155]
At https://github.com/geier/khal/issues/140 there is a user whose offset values are not accepted by icalendar. I have no idea what is going on in that iCalendar file. Anybody got any ideas?

**Comment by nielsk** [comment]
My workaround is now: https://github.com/geier/khal/issues/140#issuecomment-118461248

Cumbersome but it should  work. Looks like q quickfix only though.
Since Evolution, Lightning, Owncloud and any Android-caldav-solution I've tried have no problem with these events, any idea what they are doing?

**Comment by geier** [comment]
they probably have some clever parsing scheme that doesn't even try to
read VTIMEZONE components that they don't need to parse (as dmfs
confirmed for their android apps in the other thread)


Quoting Niels Kobschätzki (2015-07-04 06:39:08)

**Comment by petr-fischer** [comment]
Hello, +1 for some solution like "lazy parsing" due to invalid offsets from Apple serves. They  (Apple) never fix this IMHO. Some other software depends on this library, like khal calendar etc., so, give them a chance to make 100% functional software. Sometimes, we (as developers) need to fix bugs and bullshits of another party... :(  Thanks for rethink this issue!

**Comment by xkpd3** [comment]
Hello,
I'm in the same boat. I'm syncing with vdirsyncer. However, I have many read-only calendar. So correcting the offset and syncing back does not work in this case. Thanks & best regards.

**Comment by untitaker** [comment]
Hello Stefan, where is your calendar from?

On 12 September 2016 01:33:24 CEST, Stefan Hagen <notifications@github.com> wrote:
>Hello,
>I'm in the same boat. I'm syncing with vdirsyncer. However, I have many
>read-only calendar. So correcting the offset and syncing back does not
>work in this case. Thanks & best regards.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/collective/icalendar/issues/155#issuecomment-246212279

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xkpd3** [comment]
Hi untitaker,
same as from the thread-opener. My calendars are from the iCloud.

**Comment by noqqe** [comment]
Same problem here. 

```
Skipping Kalender/145C9566-A1DF-4144-90B0-8448C6EE90F6.ics: Offset must be less than 24 hours, was +5328
```
