### ISSUE TITLE
Local time (and timezone) for start/end times?

### ISSUE THREAD

**Issue by jluttine** [collective/icalendar#160]
Hi!

Is it possible to use local time and time zone in dtstart (and dtend)? My local datetime object is
```
datetime.datetime(2014,11, 5, 22, 0, tzinfo=<DstTzInfo 'Europe/Helsinki' EEST+3:00:00 DST>)
```
ICalendar converts it to UTC time and then outputs it as:
```
DTSTART;VALUE=DATE-TIME:20141105T190000Z
```
I'm not too familiar with iCalendar, but I think I'd like to have the time in local time and not in UTC, just to make sure the clients read it correctly. Or any other suggestions on what is the correct way of using local times?

**Comment by geier** [comment]
How do you create your icalendar?

this works for me:

```python
from datetime import datetime as datetime
import icalendar
import pytz

berlin = pytz.timezone('Europe/Berlin')

event = icalendar.Event()
event.add('DTSTART', berlin.localize(datetime.now()))
print event.to_ical()
```

outputs:
```
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin;VALUE=DATE-TIME:20150421T135356
END:VEVENT
```

**Comment by jluttine** [comment]
Ok, thanks! That helped me to discover a solution: Now I explicitly converted to my local timezone and it works:
```
dtstart = my_datetime_obj.astimezone(local_tzinfo)
```
So apparently, my datetime object wasn't in the correct timezone format after all..
