### ISSUE TITLE
Double newline lineendings

### ISSUE THREAD

**Issue by mathijshenquet** [collective/icalendar#166]
When I generate an (otherwise correct) ics file using icalendar the resulting file has double newline endings making it syntacticly invalid. 

The code I use:

``` python
icalFile = open(ICALFILE, 'w')
icalFile.write(cal.to_ical())
icalFile.close()
```

where `cal` is a `Calendar` object.

I'm on Windows 10 using icalendar 3.9.0

**Comment by untitaker** [comment]
What do you mean with that? icalendar shold generate `\r\n` which is the only valid form.
