### ISSUE TITLE
Parsing invalid icalendars fails without any warning

### ISSUE THREAD

**Issue by geier** [collective/icalendar#168]
Example:

```python
import icalendar

event_str = """
BEGIN:VCALENDAR
BEGIN:VEVENT
DTEND:20150905T100000Z
DTSTART:20150905T090000Z
X-APPLE-RADIUS=49.91307046514149
UID:123
END:VEVENT
END:VCALENDAR
"""

calendar = icalendar.Calendar.from_ical(event_str)
print(calendar.to_ical())
```
returns
```
BEGIN:VCALENDAR
END:VCALENDAR
```

but probably should throw an exception or at least a warning instead of ignoring the invalid VEVENT silently. Also see https://github.com/geier/khal/issues/294 .

**Comment by stlaz** [comment]
I do not think this should be referenced to that specific issue. The issue here (at least as described in the topic) is much more dire. Let me give you a nice example of where the icalendar library fails miserably without throwing an exception or giving any means to detect an error.

Suppose you have the following file (note the EXDATE date):
```
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTART;TZID=Europe/Vienna:20120327T100000
DTEND;TZID=Europe/Vienna:20120327T180000
RRULE:FREQ=WEEKLY;UNTIL=20120703T080000Z;BYDAY=TU
EXDATE;TZID=Europe/Vienna:20121329T100000
DTSTAMP:20130716T120638Z
END:VEVENT
END:VCALENDAR
```

Now, do the following in a prompt:
```python
import icalendar
cal = icalendar.Calendar.from_ical(open('icaltest', 'r').read())

print cal.to_ical()
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTART;TZID=Europe/Vienna:20120327T100000
DTEND;TZID=Europe/Vienna:20120327T180000
DTSTAMP:20130716T120638Z
EXDATE;TZID=Europe/Vienna:201213
RRULE:FREQ=WEEKLY;UNTIL=20120703T080000Z;BYDAY=TU
END:VEVENT
END:VCALENDAR

```
As you can see, not only from_ical does not fail, after calling to_ical, we get another (different) invalid iCalendar string.

**Comment by geier** [comment]
While your example is not pretty, at least the event is still there...
Anyway, for your example, the issue is [that if converting to datetime fails, we try to convert to date and than to time](https://github.com/collective/icalendar/commit/41728c3853076225ee43157f6ecc02bb4af73db3#diff-ca6ee989b93549902afff582d94e8c1eL452), but don't to any tests at all.

**Comment by stlaz** [comment]
Sorry for delayed response.
From my point of view, the fact that the event is still there is very wrong. It is wrong that the input gets through parsing.
You should definitely do the testing there. There is also a different input which I believe is wrong and passes:
```
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTART;TZID=Europe/Vienna:20120327T100000asdasdonoes
DTEND;TZID=Europe/Vienna:20120327T180000asdsadasdsad
DTSTAMP:20130716T120638Z
END:VEVENT
END:VCALENDAR
```
```
import icalendar
cal = icalendar.Calendar.from_ical(open('icaltest', 'r').read())

print cal.to_ical()
BEGIN:VCALENDAR
BEGIN:VEVENT
DTSTART;TZID=Europe/Vienna:20120327T100000
DTEND;TZID=Europe/Vienna:20120327T180000
DTSTAMP:20130716T120638Z
END:VEVENT
END:VCALENDAR

```
I saw you opened a new Issue for this. Thank you, hopefully the inputs here will prove useful :)

**Comment by thet** [comment]
Fixed by: https://github.com/collective/icalendar/pull/175
