### ISSUE TITLE
Typo and discrepancies with RFC ?

### ISSUE THREAD

**Issue by fgatbdx** [collective/icalendar#176]
I am not python expert neither a developer but for a small personnal project I looked at icalendar project. I am not 100% sure if my findings are relevant. My comments are related to ical.ics:
- in class Event(Component), the class variable singletons shows twice the property 'DTSTART'. Should not be an issue.
- in class FreeBusy(Component), the class variable singletons shows a property 'DURATION', as far as I can see in the RFC, this property is not applicable to VFREEBUSY component?
- in classes, TimezoneStandard(Component) and TimezoneDaylight(Component), the property 'EXDATE' is not specified, while it seems to be specified in RFC?
- in class Alarm(Component), the property 'DESCRIPTION' is missing, while it seems to be specified in RFC?
- In various classes, One could see the 'EXRULE' property which seems to be outdated in the RFC. Maybe it is for backward compatibility.

**Comment by stlaz** [comment]
Could you see the patch at https://github.com/stlaz/icalendar/commit/56fb1f12e3435833920e9fab3f37384962fdff3f and check, if it would make things better? No developer experience is really needed :)

**Comment by geier** [comment]
I do agree with all these changes, but as this is backwards incompatible I would defer this patch until the next major release.

**Comment by fgatbdx** [comment]
Sounds good !

**Comment by stlaz** [comment]
That's probably a good idea. I shall fix the typo in the patch as well. What is the ETA of the next major release?

**Comment by thet** [comment]
For a new major release we need some better sorted out roadmap. Currently, the README says only:
```
Roadmap

    4.0: API refactoring
``` 
... I've added that, but that's a bit sparse.
Let's start a discussion about a roadmap for a 4.0 release: https://github.com/collective/icalendar/issues/186

**Comment by thet** [comment]
Fixed with: https://github.com/collective/icalendar/pull/183
IMO PR #183 is a bugfix and doesn't really break the programmatic API of icalendar. I'll include this for the next release.

**Comment by fgatbdx** [comment]
As far as I see all comments from initial post have been taken into account.
Many thanks !
