### ISSUE TITLE
Invalid/unknown component name being substituted during parsing

### ISSUE THREAD

**Issue by stlaz** [collective/icalendar#178]
Hi,

I encountered a strange behavior in a case where there are invalid component names in an iCalendar string.

```python
>>> # the following probably shouldn't pass
>>> vcal = icalendar.Calendar.from_ical('BEGIN:THISWRONG\nSTRANGEPROP:12345\nEND:THISWRONG')
>>> # but it did
>>> vcal.to_ical()
'BEGIN:VCALENDAR\r\nSTRANGEPROP:12345\r\nEND:VCALENDAR\r\n'
```

As you can see, the parser accepted the component "THISWRONG" without any warning/error. On top of that, it represents it as a VCALENDAR component instead. This does not seem to be a correct behavior at all. It is caused by:

https://github.com/collective/icalendar/blob/master/src/icalendar/cal.py#L328

Also notice the property "STRANGEPROP" from the example. The case here is similar as "STRANGEPROP" is definitely not defined in iCalendar RFC. At least here it stays the same "STRANGEPROP" property, though.

I understand that this behavior might be there for the sake of extensibility, but at least in the first case it is not handled correctly at all. Perhaps a pluggable interface would help here but until then at least the first case should be fixed.

Opinions/comments are welcome :)

**Comment by thet** [comment]
The first case, where THISWRONG is substituded with VCALENDAR shouldn't happen, I agree. The second one in OK for me. icalendar should be able to parse properties like: ``X-LIC-LOCATION:America/New_York``, which are also non-standard.

**Comment by stlaz** [comment]
You're right, the second case is probably OK as everyone should be able to catch the invalid property later if that is required.

I might see what I can do about the other issue.

**Comment by thet** [comment]
Fixed here: https://github.com/collective/icalendar/pull/180
