### ISSUE TITLE
How to retrieve params from Attendee

### ISSUE THREAD

**Issue by mlazzje** [collective/icalendar#182]
What is the best way to retrieve params for ATTENDEE ?

` vevent.get('attendee') `

I would like to retrieve the RSVP....

```
ATTENDEE;PARTSTAT=ACCEPTED;RSVP=TRUE;X-SENT=TRUE;CN="Christian Bale";CUTYPE=INDIVIDUAL:mailto:user@domain.com
ATTENDEE;ROLE=OPT-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE;X-SENT=TRUE;CN="Emilie Rata";CUTYPE=INDIVIDUAL:mailto:user@domain.com
```

Thank you.

**Comment by stlaz** [comment]
This is more like a question to StackOverflow, it is definitely not an issue.

You have 2 attendeeds, therefore you must choose one and get theirs RSVP. So 
~~~python
vevent.get['attendee'][0].params['rsvp']
~~~
Someone close this, please.
