### ISSUE TITLE
incompatible changes in 3.9.2

### ISSUE THREAD

**Issue by geier** [collective/icalendar#184]
With 70a7b5a16748afbf0d48ca180c2b7613fdd7e7d0 we introduced some  backwards incompatible changes:

 * `Component.is_broken` got replaced with `Component.errors`
 * events with a `RDATE;VALUE=PERIOD:19970101T180000Z/19970102T070000Z,19970109T180000Z/PT5H30M` component still had an `RDATE` with `VALUE=PERIOD` param before, now they are `RDATE:None`

While I do agree with both changes, I think they should have been deferred to the 4.0.0 release. Because we don't have `VALUE=PERIOD` anyway I think we can leave this one as it is, but I believe we should bring back `Component.is_broken` for the 3.9.3 release.

**Comment by thet** [comment]
+1 for bringing back ``Component.is_broken`` and properly deprecate it. I thought, that's not used anyways and @stlaz  implementation was much better.

What about ``RDATE:VALUE=PERIOD``? If that's valid RFC5545, we should support it.

**Comment by geier** [comment]
Yes, it's valid RFC5545, but not many people seem to use it (khal prints
a warning when it finds an occurence in the wild and asks the user to
supply an example; so far nobody has turned one in).

Quoting Johannes Raggam (2016-02-15 14:17:26)

**Comment by thet** [comment]
I like flexible recurrence definitions and wasn't too happy when EXRULE fell out of RFC5545.
No time to implement that yet, though...

**Comment by stlaz** [comment]
Not sure why EXRULE was left out of RFC5545 either, it could be pretty helpful.
Also I shall look more into that PERIOD values. I noticed that there is actually a vPeriod class for these values and I think I'll need it working for my project.
