### ISSUE TITLE
UnicodeEncodeError: unable to read google agenda ics

### ISSUE THREAD

**Issue by jdh13** [collective/icalendar#190]
Hello,
in the past, i was able to parse the following ics without troubles:
https://calendar.google.com/calendar/ical/sem-signal-gestionnaire@cmi.univ-mrs.fr/public/basic.ics

but now, it fails with:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xab' in position 159: ordinal not in range(128)

`import requests`
`r = requests.get("https://calendar.google.com/calendar/ical/sem-signal-gestionnaire@cmi.univ-mrs.fr/public/basic.ics")`
`import icalendar`
`cal = icalendar.Calendar.from_ical(r.text)`

the problem seems to be related to VEVENT UID:fmbimb2tutrf9po9vqbimp9m0s@google.com, in DESCRIPTION there is "«" char that breaks the parser. (around line 138)

Is there something i am missing?

Thanks in advance for help,

gerard

**Comment by niccokunzmann** [comment]
This issue cannot be reproduced. If you would like to re-open it, please add the ICS file so it can be checked.
