### ISSUE TITLE
Test failures with python-dateutil 2.5.3

### ISSUE THREAD

**Issue by untitaker** [collective/icalendar#194]
When installing `python-dateutil==2.5.0` or newer, the tests fail:

    ======================================================================
    FAIL: test_tzinfo_dateutil (icalendar.tests.test_timezoned.TestTimezoned)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/guix-build-python-icalendar-3.9.2.drv-0/icalendar-3.9.2/src/icalendar/tests/test_timezoned.py", line 138, in test_tzinfo_dateutil
        self.assertTrue(date.tzinfo.__module__ == 'dateutil.tz')
    AssertionError: False is not true

    ----------------------------------------------------------------------
    Ran 84 tests in 0.165s

    FAILED (failures=1)

Using any older version seems to fix the problem.

cc @lfam

**Comment by lfam** [comment]
Just to clarify, I got this failure while building with python-dateutil 2.5.2.
