### ISSUE TITLE
how to delete a calendar ?

### ISSUE THREAD

**Issue by maxandersen** [collective/icalendar#216]
I can successfully create a calendar via `make_calendar` but I have not found a way to delete a calendar.

calling `cal.delete()` result in an error.

I do this:
```
client = caldav.DAVClient(url)
principal = client.principal()
calendars = principal.calendars()

for c in calendars:
    if c.name == 'orgtodo':
        c.delete()
```

which gives me:
```
Login to https://xhz:secret@p01-caldav.icloud.com:443/
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    c.delete()
  File "/usr/local/lib/python2.7/site-packages/caldav/objects.py", line 238, in delete
    raise error.DeleteError(errmsg(r))
caldav.lib.error.DeleteError: 400 Bad Request

<html><head><title>Bad Request</title></head><body><h1>Bad Request</h1><p>Client sent illegal depth header value for DELETE: 1</p></body></html>
```

Is this icloud specific or is delete broken or not the right way to do it  ?

**Comment by geier** [comment]
I'm pretty sure you meant to post this somewhere else, your issue seems
to be about a caldav library, this is `icalendar`'s issue tracker.

Quoting Max Rydahl Andersen (2017-02-21 12:48:49)

**Comment by maxandersen** [comment]
argh! sorry ;)
