### ISSUE TITLE
Maintenance / my role in this project

### ISSUE THREAD

**Issue by geier** [collective/icalendar#221]
I seem to be the most active maintainer of this project at the moment,
which is fine by me, but as I'm hesitant to merge my own PRs (as this
isn't my project and I feel for community projects such as this, whoever
works on a PR shouldn't also be merging it), bugs get fixed very slowly.
New features, especially backwards compatibility breaking ones obviously
get merged even slower, if they are getting worked on at all.

If nobody has time to review at least the bug fixing PRs, it would
perhaps be better if I did at least merge bug fixing PRs (and you don't
shout too loudly at me if I break anything)?

Other maintainers, what are your opinions?

**Comment by untitaker** [comment]
cc @thet @regebro (since you've been around longer), I'm also interested in the answer to this.

**Comment by regebro** [comment]
I haven't touched it in years, but my opinion is that if nobody reviews your merge requests and it passes tests, then merge it. Don't worry too much about breakage, that's what revision control is for.

**Comment by geier** [comment]
Thanks for clarification!
