### ISSUE TITLE
tzoffset information lost

### ISSUE THREAD

**Issue by pgiraud** [collective/icalendar#239]
I'm creating a date with an utcoffset, like so:

```python
>>> import dateutil
>>> date = dateutil.parser.parse('2017-09-06T09:00:00+02:00')
>>> date
datetime.datetime(2017, 9, 6, 9, 0, tzinfo=tzoffset(None, 7200))
>>> from icalendar import Event
>>> event = Event()
>>> event.add('dtstart', date)
>>> event.to_ical()
'BEGIN:VEVENT\r\nDTSTART;VALUE=DATE-TIME:20170906T090000\r\nEND:VEVENT\r\n'
```

In the generated ical, I don't have the information about the offset anymore.
Am I doing something wrong?

**Comment by natashamm** [comment]
I think this can be closed because this is not supported in RFC 5545 - see https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.5

> The form of date and time with UTC offset MUST NOT be used.

**Comment by pgiraud** [comment]
Idle. Closing.
