### ISSUE TITLE
Empty feed fails validation

### ISSUE THREAD

**Issue by oppianmatt** [collective/icalendar#251]
Thanks to rfc5545 3.4 https://tools.ietf.org/html/rfc5545#page-50 a calendar must contain at least one object. So when we have an empty icalendar object it fails validation.

But if a calendar truly doesn't have any events, how are we meant to offer a feed that validates?

For example an empty/basic calendar looks like:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Bookings Calendar//example.com//8690841
END:VCALENDAR
```

But that fails validation with some icalendar readers. What's the correct thing to do in this situation.

**Comment by geier** [comment]
I have no idea, sorry. As this is not really an icalendar (as in this library) problem, I'll close this issue.

Where you might be able to get help, is [calconnect's  developer mailing list](https://www.calconnect.org/resources/discussion-lists).
