### ISSUE TITLE
how can i search events with rrule?

### ISSUE THREAD

**Issue by hiwjcn** [collective/icalendar#252]
how can i search events with rrule?

thanks for your contributions

**Comment by jonasius** [comment]
@hiwjcn 
I think you could go through your cal data with `walk()` and then use `get('RRULE')` to get your rrule data.

example:
```
icsFh = open(icsFile, 'rb')
cal = Calendar.from_ical(icsFh.read())
for d in cal.walk():
  rrule = d.get('RRULE')
```
is that what you needed?

**Comment by geier** [comment]
yes, @jonasius's answer is the only one I know of.
