### ISSUE TITLE
Command line interface.

### ISSUE THREAD

**Issue by jfjlaros** [collective/icalendar#255]
I wrote a simple command line interface for use in terminal based e-mail clients like mutt. Would you be interested in a pull request?

**Comment by thet** [comment]
sounds interesting. what does the CLI do?
In general, PR's are alyways welcome.

**Comment by jfjlaros** [comment]
It writes a human readable summary (organiser, attendees, start and end time, description, etc.) of an event to a stream (stdout by default). I have been using a similar tool for years to read invitations in mutt.

When I found your library, it seemed like a good idea to toss out my parser and rewrite this tool.

**Comment by thet** [comment]
closed via  #256
