### ISSUE TITLE
Events happening today

### ISSUE THREAD

**Issue by PabloCastellano** [collective/icalendar#257]
I would love to have a way of knowing the events happening today (or in some specific day). Is there a way to get them other than looping over all the events and checking the date myself?

(I guess no)

I could implement this feature if you consider it useful as well. However for normal events it is a piece of cake but for recurring events, what is the easiest way to do it?

**Comment by PabloCastellano** [comment]
I just found out [icalevents](https://github.com/irgangla/icalevents), which is built on top of icalendar and does exactly this!

I'm going to prepare a PR to advertise it in icalendar's README

**Comment by thet** [comment]
Nice finding! I did not know about this project - looks quite useful.
