### ISSUE TITLE
Problems with latest python-dateutil

### ISSUE THREAD

**Issue by jensens** [collective/icalendar#260]
I tried to update our Plone dependencies to *python-dateutil 2.7.2* which broke, see plone/buildout.coredev#447

I found it is an icalendar issue. Also icalendar Travis CI https://travis-ci.org/collective/icalendar/builds/361592061is red.

**Comment by kyrias** [comment]
Been looking into this for a bit now, and it seems like the dateutil exception is actually lying.  The rules in question seems to have a DTSTART without a timezone and a UNTIL in UTC, but the exception claims otherwise.  Will try to ask the dateutil people about this.

**Comment by kyrias** [comment]
Reading RFC 5545 a bit closer it seems that the dateutil exception is indeed misleading, and it's the test case that's wrong.

```

**Comment by legrostdg** [comment]
What is the recommendation for this test? Should it be disabled? python-icalendar (and its reverse dependencies) will be removed soon from Debian... https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908498

**Comment by jensens** [comment]
This is solved for now, follow up see #274

**Comment by legrostdg** [comment]
Would it be possible to do a new release with this fix? This would help Debian packaging. Thanks!

**Comment by jensens** [comment]
@esteele @mauritsvanrees @thet can we have a release of the latest fixes please?

**Comment by mauritsvanrees** [comment]
There you go: https://pypi.org/project/icalendar/4.0.3/

**Comment by legrostdg** [comment]
Great, thanks!
