### ISSUE TITLE
icalendar Web site lost format

### ISSUE THREAD

**Issue by salvadorsosa** [collective/icalendar#264]
The project website http://icalendar.readthedocs.org/ lost its format. 
This happened some weeks ago, but still is without format.

**Comment by salvadorsosa** [comment]
I did some additional research and the problem is not directly in your site. You are using a template provided by readthedocs.org and reaching the resources thru https (the right way), but the digital certificate from *.readthedocs.org used in cdnmedia.readthedocs.org expired 68 days ago.  Now browsers don't load the shared web site theme unless the users instruct to allow "insecure" connections to cdnmedia.readthedocs.org. I think I will put the issue in other forum, but in the mean time if you can change the site theme would be good. Thanks.

**Comment by ololosha228** [comment]
i think, that this project is abadoned, so needs to try fork it. i think.

**Comment by jrast** [comment]
Seems like some commits where done in the last month, but nothing is going on in the issue tracker... @mauritsvanrees please have a look at this.

**Comment by mauritsvanrees** [comment]
I occasionally create a release because `icalendar` is used by Plone and I am in the Plone Release Team. But I don't know the package internals, so I don't look at the issue tracker.

I also don't know how to fix the site theme or certificate on 
http://icalendar.readthedocs.org/

@thet Do you have an idea how to fix that, or who else to ask?

**Comment by RagingRoosevelt** [comment]
@mauritsvanrees, it looks like it's there's an article about RTD theming [here](https://docs.readthedocs.io/en/rel/theme.html).  I'm still trying to figure out what exactly needs to be changed but it appears that adjusting the [docs/conf.py](https://github.com/collective/icalendar/blob/master/docs/conf.py) file might be the place to look.

It looks like someone [started an issue](https://github.com/readthedocs/readthedocs.org/issues/4082) on the readthedocs's repo about icalendar.  I think someone from RTDs submitted an iCalendar pull request #289 that attempted to fix the issue.  The PR was approved but looks like it hasn't been merged yet.

**Comment by mauritsvanrees** [comment]
I have merged the PR. Let's see if the website improves. It hasn't yet, but that can probably take a bit of time.

**Comment by RagingRoosevelt** [comment]
[It looks like](https://travis-ci.org/collective/icalendar) it has a failing build which must be preventing the RTD stuff from getting built?  I'm not very familiar with how CICD stuff works or TravisCI in particular but I'll try to make sense of it when I get home from work later today.
