### ISSUE TITLE
Support "All day" events

### ISSUE THREAD

**Issue by LukasGrebe** [collective/icalendar#269]
Looking through the documentation, i did not find an example of all day events.
I would love to see `DTSTART;VALUE=DATE:20100101` instead of Date Time values 

See also: https://stackoverflow.com/a/30249034

**Comment by LukasGrebe** [comment]
nevermind, i had a bug in my code and am now getting the expected `DTSTART;VALUE=DATE: 20100101 `
#ruberduckdebugging

**Comment by wnma3mz** [comment]
@LukasGrebe I also meet the same problem now. Can you tell me how you did it? Thx!

**Comment by wnma3mz** [comment]
Well, I slove that. The `datetime.date()` can help me. Anyway, thank you.
