### ISSUE TITLE
Document Page Still Broken

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [collective/icalendar#270]
It is ~~8102~~ 2018 now and the doc page is still suffering from expired certificate of [cdnmedia.readthedocs.org](https://cdnmedia.readthedocs.org) . So js and css still not loads.

Edit: It is ~~9102~~ 2019 now....

**Comment by chrisconlan** [comment]
Looks bad and make me not trust this otherwise helpful package. Please fix.

**Comment by Lx** [comment]
For anyone wanting to view the docs properly, a workaround is to try to visit one of the affected resources directly:

https://cdnmedia.readthedocs.org/css/sphinx_rtd_theme.css

and "trust" or otherwise "authorise" that resource to be visited.  After this, the docs display correctly.

**Comment by RagingRoosevelt** [comment]
Duplicate of #264
