### ISSUE TITLE
Looking for a simple way to parse a list of events 

### ISSUE THREAD

**Issue by ghost** [collective/icalendar#275]
I'm simply looking to export a Google list of events as plain text to be TTSd for a blind person.
I've yet to find a project which can handle rrules, but I saw this project had a related project called [icalevents](https://github.com/irgangla/icalevents).

Unfortunately, there's close to zero documentation or support on that project, all it says is (replacing demo with my test calendar here)

```
from icalevents.icalevents import events
es  = events('https://calendar.google.com/calendar/ical/ssjqjrg27h9mqqctfnr5kscmrk%40group.calendar.google.com/public/basic.ics');
```

Well, of course, that does nothing on its own. So I added `print(es);`

I'm a bit of a python noob, and I'm sorry but I have absolutely no idea what to do with this output:

```
[<icalevents.icalparser.Event object at 0x7fb526e1d438>, <icalevents.icalparser.Event object at 0x7fb526e1d4e0>, <icalevents.icalparser.Event object at 0x7fb526e1d4a8>, <icalevents.icalparser.Event object at 0x7fb526e1d5f8>, <icalevents.icalparser.Event object at 0x7fb526e1d588>, <icalevents.icalparser.Event object at 0x7fb526e1d630>, <icalevents.icalparser.Event object at 0x7fb526e1d668>, <icalevents.icalparser.Event object at 0x7fb526e1d6a0>, <icalevents.icalparser.Event object at 0x7fb526e1d6d8>]
```

If anyone can give me some pointers, I'd be really greatful

**Comment by jacadzaca** [comment]
from [cli.py](https://github.com/collective/icalendar/blob/master/src/icalendar/cli.py#L73)

```python
with open(calendar_file) as f:
    calendar = Calendar.from_ical(#ical content#)
    for event in calendar.walk('vevent'):
        # do stuff to events
```
