### ISSUE TITLE
VALARM in Events

### ISSUE THREAD

**Issue by tedpelas** [collective/icalendar#276]
I have tried to search for VALARM examples and looked through the code a bit, but I have not found how to accomplish the following in an calendar event with the icalendar lib.

Is it possible to add the following to an Event with icalendar?
```
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-P1D
END:VALARM
```

Thank you!

**Comment by Skyy93** [comment]
need the same 👍

**Comment by geier** [comment]
Have a look at how  we do it in khal: https://github.com/pimutils/khal/blob/1bc431f5390b280d1f162131f592cde03028fabb/khal/khalendar/event.py#L397

**Comment by Eluminae** [comment]
Hello ! I'm using [remhind](https://github.com/nicoe/remhind) that is using icalendar but it seems it cannot use the VALARM. Is this feature implemented?

**Comment by Eluminae** [comment]
Okay my problem was elsewhere. We got to handle this kind of relative date by our hand. Mr to remhind   https://github.com/nicoe/remhind/pull/2
