### ISSUE TITLE
Which RFC is icalendar attempting to implement?

### ISSUE THREAD

**Issue by ghost** [collective/icalendar#278]
https://github.com/collective/icalendar/blob/master/docs/usage.rst says:

> This package is used for parsing and generating iCalendar files following the standard in **RFC 2445**.

OTOH, #183 says:

> Updated components to better conform to **RFC 5545**

So, which of these two RFCs is the *icalendar* Python module actually attempting to implement? Should the docs be updated to say "5545" instead of "2445"?

**Comment by niccokunzmann** [comment]
I think, the docs can be updated to say 5545. People expect this and if the documentation states it, it is clear that 5545 should be achieved.
