### ISSUE TITLE
Attachment parsing

### ISSUE THREAD

**Issue by chris246** [collective/icalendar#290]
According to the [RFC](https://tools.ietf.org/html/rfc5545#section-3.8.1.1), an ATTACHMENT can have additional, optional properties, as e.g.
`ATTACH;FMTTYPE=application/postscript:ftp://example.com/pub/reports/r-960812.ps`
The currently used vUri Class does not expose these Attributes.

In my use case, I need them to access attachment information as the file name and its mime type.

In a quick-and-dirty hack, I modified the vUri class to return a tuple:
`[ATTACHMENT, Parameters(...)]`, but this will break things.

Is there a possibility to add this feature without breaking stuff?

**Comment by luckydonald** [comment]
I'm also not able to write a valid attachment.

**Comment by jacadzaca** [comment]
as per #295
```python
event = Event()
uri = vUri('ftp://example.com/pub/reports/r-960812.ps')
uri.params['FMTTYPE'] = 'application/postscript'
event.add('attach', uri)
print(event.to_ical())
```

results in...

```
BEGIN:VEVENT\r\nATTACH;FMTTYPE=application/postscript:ftp://example.com/pub/reports/r-9608\r\n 12.ps\r\nEND:VEVENT\r\n
```
which is correct
