### ISSUE TITLE
CSS not loading on documentation

### ISSUE THREAD

**Issue by dullbananas** [collective/icalendar#302]
When I try loading the readthedocs documentation for this, the css appears to be missing

**Comment by RagingRoosevelt** [comment]
It seems like this is a SSL cert issue.  I tried to load some of the asset files and I get a `NET::ERR_CERT_DATE_INVALID` error (eg see [here](https://assets.readthedocs.org/static/javascript/underscore.js)).   If I load the link itself and then select "accept the risk" it will load and then so will the rest of the page.  But that doesn't seem like the correct fix.

**Comment by RagingRoosevelt** [comment]
Duplicate of #264
