### ISSUE TITLE
icalendar fails parsing some RRULE based timezone definitions

### ISSUE THREAD

**Issue by simon-budig** [collective/icalendar#303]
Some timezone definitions fail parsing. One example is the testcase "test_create_america_new_york" in the current testsuite, which is right now marked unittest.expectedFailure.

Underlying reason is that evaluating the RRULE in some cases is done with mixed offset-awareness, datetime.rrule can't handle that (see e.g. https://github.com/dateutil/dateutil/issues/851),
I've prepared a pull request to fix this. The patch evaluates the rrule with the relevant TZOFFSETFROM from the timezone description. This avoids this problem.

**Comment by thet** [comment]
Closed by: https://github.com/collective/icalendar/pull/304

**Comment by mauritsvanrees** [comment]
I have released 4.0.7 with the fix.
Thanks!
