### ISSUE TITLE
how convert an ics to md, if (many) vevents don't have category

### ISSUE THREAD

**Issue by DoctorSubtilis** [collective/icalendar#317]
I get an error message when I try to convert an ics calendar, whose (many) vevents are without category.   
The message is  

      File "/usr/local/lib/python3.8/dist-packages/ics/component.py", line 54, in _populate
      raise ValueError(
     ValueError: A VEVENT must have at most one CATEGORIES

I use a Python 3 script to convert ics to md:

    from ics import Calendar

    md_template = """
    ### {start}
    *{name}*: {desc}""" 

    with open("diario.ics") as f:
       cal = Calendar(f.read())

    print("## Diario")
    for e in sorted(cal.events):
    print(md_template.format(start=e.begin.strftime("%Y-%m-%e"), name=e.name, 
                             desc=e.description))

There is a workaround to avoid this behavior, without add manually a category to every vevent (quite boring)?

**Comment by jacadzaca** [comment]
I presume you wanted to achieve something like this...

```python
from icalendar import Calendar

md_template = """
### {start}
*{name}*: {desc}"""

with open("sample.ics") as f:
   cal = Calendar.from_ical(f.read())

print("## Diario")
for event in cal.walk('vevent'):
    print(md_template.format(start=e.decoded('dtstart').strftime("%Y-%m-%e"),
                             name=event.get('summary'),
                             desc=event.get('description')))
```
