### ISSUE TITLE
Skip VALUE properties when using the default value

### ISSUE THREAD

**Issue by dilyanpalauzov** [collective/icalendar#318]
As outlined at https://github.com/indico/indico/issues/4783 when the iCalendar library is used to generate iCalendar data it includes the default VALUE property parameter.  This increases the amount of exchanged data without having added value.

In the example, generated by iCalendar:
```
DTSTART;VALUE=DATE-TIME:20190616T050000Z
DTEND;VALUE=DATE-TIME:20190620T153000Z
DTSTAMP;VALUE=DATE-TIME:20210217T082500Z
```
`;VALUE=DATE-TIME` should be absent.

**Comment by niccokunzmann** [comment]
@dilyanpalauzov , я писал три теста для этого в #450 и если вы хотите, можете составить PR и участвовать в Hacktoberfest.

I wrote three tests for this in #450 and if you like, you can create a pull request and participate in Hacktoberfest.
