### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [collective/icalendar#323]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine src/icalendar/cal.py, src/icalendar/tests/test_property_params.py and observe `seperated`, however expect to see `separated`.
- Examine src/icalendar/timezone_cache.py and observe `unknow`, however expect to see `unknown`.
- Examine src/icalendar/tests/test_unit_cal.py and observe `subcompont`, however expect to see `subcomponent`.
- Examine src/icalendar/tests/test_property_params.py and observe `seperately`, however expect to see `separately`.
- Examine src/icalendar/tests/test_property_params.py and observe `recieved`, however expect to see `received`.
- Examine src/icalendar/cal.py and observe `directy`, however expect to see `directly`.
- Examine src/icalendar/cal.py and observe `complience`, however expect to see `compliance`.
- Examine src/icalendar/tests/test_fixed_issues.py and observe `icalender`, however expect to see `icalendar`.
- Examine src/icalendar/tests/test_icalendar.py and observe `allwoed`, however expect to see `allowed`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/icalendar/pull/new/bugfix_typos

Thanks.

**Comment by rohnsha0** [comment]
Hey @timgates42! 
I personally don't think the issues reported by you deserves much attention, as all are just comments. Those won't throw any errors or stuffs like that.

**Comment by niccokunzmann** [comment]
@timgates42 I would be happy to see several pull requests from you if you are willing to do that. Several - because if one is controversial, it does not block the rest of your edits.
As you are a first-time contributor, no CI will run for this, I believe.

**Comment by rohnsha0** [comment]
I'll push a PR correcting suggested changes

**Comment by rohnsha0** [comment]
#383 Kindly check the changes @timgates42 @niccokunzmann

**Comment by geier** [comment]
fixed with https://github.com/collective/icalendar/issues/323
