### ISSUE TITLE
Readthedocs documentation?

### ISSUE THREAD

**Issue by sigma67** [collective/icalendar#325]
First off, thanks for this great project! Some feedback regarding accessbility: For newcomers it is very hard to get into the project since no documentation is linked either on PyPi or on the GitHub homepage.

Using Google I found https://icalendar.readthedocs.io/en/latest/ which was quite helpful. However, this page should be linked in the README and on PyPI. The RTD docs also do not seem to be based on the latest version (page title states 4.0.5dev0).

**Comment by opk12** [comment]
`>>> help(icalendar.Calendar)` etc. also proved helpful to me. I'm leaving this for posterity.

**Comment by djbrown** [comment]
@niccokunzmann this issue may be closed as complete since the documentation is already linked in [README.rst ](https://github.com/collective/icalendar/blob/master/README.rst?plain=1#L10) and PyPI

**Comment by djbrown** [comment]
Not sure if it's the same problem, but the README on PyPI is also outdated https://pypi.org/project/icalendar/
It shows the build-failing badge of the historic travis-ci build

**Comment by niccokunzmann** [comment]
TODO:

- [ ] update read the docs - thanks for pointing this out! - a task for the maintainers...
- [ ] update PyPI (this should be updated with a new release)

**Comment by niccokunzmann** [comment]
@mauritsvanrees Is there a way that we can get access to the readthedocs configuration?

It looks like it needs a bit of configuration:
https://readthedocs.org/projects/icalendar/builds/
![image](https://user-images.githubusercontent.com/564768/193678158-7de9041d-edbb-4c3b-a781-4ef67912d72a.png)

**Comment by niccokunzmann** [comment]
@thet and @garbas - would it be possible for @geier and @niccokunzmann to get access to the readthedocs documentation for icalendar? https://readthedocs.org/projects/icalendar/
We are both new maintainers of this repository, according to https://github.com/collective/icalendar/discussions/360
I ask you two directly as nobody else has access.

**Comment by garbas** [comment]
@niccokunzmann I'll check what can I do.

**Comment by garbas** [comment]
I think I've sent you the invitation to be the maintainer. Please let me know if it worked out. Also once you are the maintainer please remove me from Maintainers list.

**Comment by niccokunzmann** [comment]
> Also once you are the maintainer please remove me from Maintainers list.

It worked! I removed you!

**Comment by niccokunzmann** [comment]
The current documentation builds, the 4.x branch and the master branch.
A web hook is active to trigger new builds when a push is made.
![image](https://user-images.githubusercontent.com/564768/193938799-02e6d5e5-c295-4ae6-ae24-1393301f54bc.png)


Once #430 is merged and we see that the new documentation has arrived, I would consider this tested and closed.
