### ISSUE TITLE
:bug There is no'\,' in the original text, but'\,' appears in the exported ics file

### ISSUE THREAD

**Issue by sdy623** [collective/icalendar#326]
Environment :Windows NT 10.0 19042.1110 
Python 3.7.10 with icalendar  4.0.7.
This is my python code section
`   if "aaa" in courseRoom :
            event.add('X-APPLE-STRUCTURED-LOCATION','geo:19.19810,114.514', parameters={'VALUE': 'URI', 'X-APPLE-MAPKIT-HANDLE': '','X-APPLE-RADIUS':'80','X-TITLE':'aaa'})`
Section of Exported ics file 
`LOCATION:aaa
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-MAPKIT-HANDLE=;X-APPLE-RADIU
 S=80;X-TITLE=aaa:geo:1919.810\,114.514`
I found that if a ',' appears ,the output file appears a '\,' why this problem occurs and how to solve the problem.
Thanks.

**Comment by 2010019970909** [comment]
I think it is to escape `,` (see the [RFC5545](https://www.ietf.org/rfc/rfc5545.txt#:~:text=encodes%20newline%0A%20%20%20%20%20%20%20%20%20%20%3B%20%5C%3B%20encodes%20%3B%2C-,%5C%2C%20encodes%20%2C,-TSAFE%2DCHAR%20%3D%20WSP)).

You can read:
>        ESCAPED-CHAR = ("\\" / "\;" / "\," / "\N" / "\n")
>           ; \\ encodes \, \N or \n encodes newline
>           ; \; encodes ;, \, encodes ,

Did it cause any issue?
