### ISSUE TITLE
 how to automatically create event on google calendar

### ISSUE THREAD

**Issue by paulorobsant** [collective/icalendar#341]
I would like to know if there is any way for me to create an event within google calendar without the need for the user to enter the email and accept the event I sent.

**Comment by jacadzaca** [comment]
This issue will be closed as it's out of scope of this module. I think that the functionality can be achieved by __using__ icalendar, so  if still need a hand implementing it, you can start a [disccusion here](https://github.com/collective/icalendar/discussions) or ask for help on some other programming forum. If you choose to start a discussion, please link it in a comment, so people facing a similar problem have easier time finding it.

**Comment by abe-101** [comment]
Consider looking into the google calendar [API](https://developers.google.com/calendar/api/guides/overview) .
