### ISSUE TITLE
X-WR-TIMEZONE - disussion

### ISSUE THREAD

**Issue by niccokunzmann** [collective/icalendar#343]
I maintain [python-recurring-ical-events](https://github.com/niccokunzmann/python-recurring-ical-events/) and already 3 Issues were reported about `X-WR-TIMEZONE` expectations, see Issue https://github.com/niccokunzmann/python-recurring-ical-events/issues/71.

My question is where to support X-WR-TIMEZONE as
- it is not in the standard.
- People who do not now it, will run into wrong assumptions with their calendars. 
- This library `icalendar` uses `pytz` time zones from the database, as I understand, not the ones in the TIMEZONE definitions, correct?

It looks like X-WR-TIMEZONE **is** not be supported by `icalendar` and also **should not** be supported.
By "supported", I mean that the times of the dates without time zone receive the time zone of X-WR-TIMEZONE.

About approching this:
I see these places to support X-WR-TIMEZONE:
- `icalendar`
- `python-recurring-ical-events`
    - this duplicates behaviour: `icalevents` also checks for X-WR-TIMEZONE 
    - people might just want X-WR-TIMEZONE without any of that recurrence interpretation
- a new module on pypi, dedicated to X-WR-TIMEZONE

What do you think about these options, especially the first one?

**Comment by niccokunzmann** [comment]
I created a library `x-wr-timezone` to check out what it takes to work on this. https://github.com/niccokunzmann/x-wr-timezone

**Comment by NicoHood** [comment]
Actually a pretty nice idea!
