### ISSUE TITLE
Test failure on Python 3.11

### ISSUE THREAD

**Issue by limburgher** [collective/icalendar#344]
python-icalendar fails to build with Python 3.11.0a2.

=================================== FAILURES ===================================
___________________ IcalendarTestCase.test_contentline_class ___________________

self = <icalendar.tests.test_icalendar.IcalendarTestCase testMethod=test_contentline_class>

    def test_contentline_class(self):
        from ..parser import Contentline, Parameters
        from ..prop import vText
    
        self.assertEqual(
            Contentline('Si meliora dies, ut vina, poemata reddit').to_ical(),
            b'Si meliora dies, ut vina, poemata reddit'
        )
    
        # A long line gets folded
        c = Contentline(''.join(['123456789 '] * 10)).to_ical()
        self.assertEqual(
            c,
            (b'123456789 123456789 123456789 123456789 123456789 123456789 '
             b'123456789 1234\r\n 56789 123456789 123456789 ')
        )
    
        # A folded line gets unfolded
        self.assertEqual(
            Contentline.from_ical(c),
            ('123456789 123456789 123456789 123456789 123456789 123456789 '
             '123456789 123456789 123456789 123456789 ')
        )
    
        # http://tools.ietf.org/html/rfc5545#section-3.3.11
        # An intentional formatted text line break MUST only be included in
        # a "TEXT" property value by representing the line break with the
        # character sequence of BACKSLASH, followed by a LATIN SMALL LETTER
        # N or a LATIN CAPITAL LETTER N, that is "\n" or "\N".
    
        # Newlines are not allwoed in content lines
        self.assertRaises(AssertionError, Contentline, b'1234\r\n\r\n1234')
    
        self.assertEqual(
            Contentline('1234\\n\\n1234').to_ical(),
            b'1234\\n\\n1234'
        )
    
        # We do not fold within a UTF-8 character
        c = Contentline(b'This line has a UTF-8 character where it should be '
                        b'folded. Make sure it g\xc3\xabts folded before that '
                        b'character.')
    
        self.assertIn(b'\xc3\xab', c.to_ical())
    
        # Another test of the above
        c = Contentline(b'x' * 73 + b'\xc3\xab' + b'\\n ' + b'y' * 10)
    
        self.assertEqual(c.to_ical().count(b'\xc3'), 1)
    
        # Don't fail if we fold a line that is exactly X times 74 characters
        # long
        c = Contentline(''.join(['x'] * 148)).to_ical()
    
        # It can parse itself into parts,
        # which is a tuple of (name, params, vals)
        self.assertEqual(
            Contentline('dtstart:20050101T120000').parts(),
            ('dtstart', Parameters({}), '20050101T120000')
        )
    
        self.assertEqual(
            Contentline('dtstart;value=datetime:20050101T120000').parts(),
            ('dtstart', Parameters({'VALUE': 'datetime'}), '20050101T120000')
        )
    
        c = Contentline('ATTENDEE;CN=Max Rasmussen;ROLE=REQ-PARTICIPANT:'
                        'MAILTO:maxm@example.com')
        self.assertEqual(
            c.parts(),
            ('ATTENDEE',
             Parameters({'ROLE': 'REQ-PARTICIPANT', 'CN': 'Max Rasmussen'}),
             'MAILTO:maxm@example.com')
        )
        self.assertEqual(
            c.to_ical().decode('utf-8'),
            'ATTENDEE;CN=Max Rasmussen;ROLE=REQ-PARTICIPANT:'
            'MAILTO:maxm@example.com'
        )
    
        # and back again
        # NOTE: we are quoting property values with spaces in it.
        parts = ('ATTENDEE',
                 Parameters({'ROLE': 'REQ-PARTICIPANT',
                             'CN': 'Max Rasmussen'}),
                 'MAILTO:maxm@example.com')
        self.assertEqual(
            Contentline.from_parts(*parts),
            'ATTENDEE;CN="Max Rasmussen";ROLE=REQ-PARTICIPANT:'
            'MAILTO:maxm@example.com'
        )
    
        # and again
        parts = ('ATTENDEE', Parameters(), 'MAILTO:maxm@example.com')
        self.assertEqual(
            Contentline.from_parts(*parts),
            'ATTENDEE:MAILTO:maxm@example.com'
        )
    
        # A value can also be any of the types defined in PropertyValues
        parts = ('ATTENDEE', Parameters(), vText('MAILTO:test@example.com'))
        self.assertEqual(
            Contentline.from_parts(*parts),
            'ATTENDEE:MAILTO:test@example.com'
        )
    
        # A value in UTF-8
        parts = ('SUMMARY', Parameters(), vText('INternational char Ã¦ Ã¸ Ã¥'))
        self.assertEqual(
            Contentline.from_parts(*parts),
            'SUMMARY:INternational char Ã¦ Ã¸ Ã¥'
        )
    
        # A value can also be unicode
        parts = ('SUMMARY', Parameters(), vText('INternational char Ã¦ Ã¸ Ã¥'))
        self.assertEqual(
            Contentline.from_parts(*parts),
            'SUMMARY:INternational char Ã¦ Ã¸ Ã¥'
        )
    
        # Traversing could look like this.
        name, params, vals = c.parts()
        self.assertEqual(name, 'ATTENDEE')
        self.assertEqual(vals, 'MAILTO:maxm@example.com')
        self.assertEqual(
            sorted(params.items()),
            sorted([('ROLE', 'REQ-PARTICIPANT'), ('CN', 'Max Rasmussen')])
        )
    
        # And the traditional failure
>       with self.assertRaisesRegexp(
            ValueError,
            'Content line could not be parsed into parts'
        ):
E       AttributeError: 'IcalendarTestCase' object has no attribute 'assertRaisesRegexp'

src/icalendar/tests/test_icalendar.py:168: AttributeError
=========================== short test summary info ============================
FAILED src/icalendar/tests/test_icalendar.py::IcalendarTestCase::test_contentline_class
========================= 1 failed, 95 passed in 0.45s =========================

**Comment by hroncok** [comment]
The casue:

> Removed many old deprecated unittest features:
>     TestCase method aliases failUnlessEqual, failIfEqual, failUnless, failIf, failUnlessRaises, failUnlessAlmostEqual, failIfAlmostEqual (deprecated in Python 3.1), assertEquals, assertNotEquals, assert_, assertAlmostEquals, assertNotAlmostEquals, assertRegexpMatches, assertRaisesRegexp (deprecated in Python 3.2), and assertNotRegexpMatches (deprecated in Python 3.5).
>     Undocumented and broken TestCase method assertDictContainsSubset (deprecated in Python 3.2).
>     Undocumented <unittest.TestLoader.loadTestsFromModule> TestLoader.loadTestsFromModule() parameter use_load_tests (deprecated and ignored since Python 3.2).
>     An alias of the TextTestResult class: _TextTestResult (deprecated in Python 3.2).

(Contributed by Serhiy Storchaka in bpo-45162.)

https://bugs.python.org/issue45162
https://docs.python.org/3.11/whatsnew/3.11.html

**Comment by tirkarthi** [comment]
PR : https://github.com/collective/icalendar/pull/330
