### ISSUE TITLE
Future of icalendar, looking for maintainer

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/icalendar#361]
I have created a [post on the Plone community forum](https://community.plone.org/t/future-of-icalendar-looking-for-maintainer/15445) about the future of this package, and needing a maintainer for it.

If you want to add your thoughts, please create an account and comment there.
Actually, let me open op discussions in this repository: https://github.com/collective/icalendar/discussions/360
You are still welcome in the Plone community forum of course. :-)

**Comment by valberg** [comment]
There is always https://jazzband.co/ which might be a good fit for icalendar?

**Comment by mauritsvanrees** [comment]
Thanks for the suggestion. That is a nice organisation too. But I doubt moving a project from one big organisation to another big organisation makes a difference. The goals are not really different. There should be enough people in the collective to maintain this, and it is easy for others to join. I think people just are not aware. I myself was not aware that this package is used so much.

**Comment by valberg** [comment]
Ah right! I didn't register that it was already a part of an organisation :)

**Comment by niccokunzmann** [comment]
@valberg I commented in the discussion https://github.com/collective/icalendar/discussions/360#discussioncomment-3344908 and wonder what your thoughts are.

**Comment by niccokunzmann** [comment]
As we have a set of maintainers and a discussion as pointed out above, I will close this now. Feel free to comment or re-open if that feels right for you (the reader).
