### ISSUE TITLE
v4.1.0 details missing from `CHANGES.rst`

### ISSUE THREAD

**Issue by Lx** [collective/icalendar#393]
[v4.1.0 has been released to PyPI](https://pypi.org/project/icalendar/4.1.0/) but there's no corresponding section in the [changelog on `master` at this time](https://github.com/collective/icalendar/blob/d89d962787ca67624aaca9d0634b9deeb92bfced/CHANGES.rst).

**Comment by geier** [comment]
Thanks for pointing this out. The Changes in 4.1.0 are the same as in 5.0.0a1 (which are noted in the changelog), I'll send a PR.
