### ISSUE TITLE
test_issue_335_identify_UTC fails?

### ISSUE THREAD

**Issue by jacadzaca** [collective/icalendar#397]
Running test_issue_335_identify_UTC fails on my machine. Seems to be a timezone issue, since the diff shows that the dates are an hour apart. Any idea why that is?

[Full testlog](https://github.com/collective/icalendar/files/9528969/testlog.txt)

**Comment by jacadzaca** [comment]
I think the issue is in  [line 506](https://github.com/collective/icalendar/blob/master/src/icalendar/tests/test_fixed_issues.py#L506), since [astimezone actually converts the given datetime to the timezone](https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone)

If I change line line 505 to `dt = datetime.datetime(2021, 11, 17, 15, 9, 15, tzinfo=zone)` and line 506 to `myevent.add('dtstart', dt)` the tests pass, so it must be it

**Comment by niccokunzmann** [comment]
Hm. Is this changed in the tests in the master branch? I would close it then. The test code might be wrong.

**Comment by niccokunzmann** [comment]
Ah. OK. The app I am using does not show the link to the merged PR. Alright.
