### ISSUE TITLE
New Release 5.0.0

### ISSUE THREAD

**Issue by niccokunzmann** [collective/icalendar#429]
@geier - let's discuss the next release of the project and what is necessary for it.

I think, I would release `v5.0.0` as we have some nice new features with it and the changelog is growing.
I do not think that holding the changes back will benefit people who are not installing the alpha release `5.0.0a1` either way because how would you know? I would't check all my 100 dependencies for alpha releases.

I am happy to get into a fast-release cycle eventually implementing pushing new releases automatedly (other issue/PR).

What are your (everyone's) thoughts on this? Are there any concerns?

Related:
- https://github.com/collective/icalendar/issues/396
- #355

**Comment by niccokunzmann** [comment]
I created #430 to document how to go about new releases.

**Comment by mauritsvanrees** [comment]
I have run the core Plone 6.0 tests with a checkout of `icalendar` and they are green. (Some GitHub actions have errors, but that is completely unrelated.) So from a Plone viewpoint there seems to be no problem in having a new release.
Thanks for all your work so far!

**Comment by niccokunzmann** [comment]
Releasing ...

**Comment by niccokunzmann** [comment]
Documentation is up-to-date.
I am working on the tagged release process....
https://github.com/niccokunzmann/icalendar/actions/runs/3263793356/jobs/5363451826#step:8:39

**Comment by niccokunzmann** [comment]
Uhh.... 
![image](https://user-images.githubusercontent.com/564768/196142701-41741190-5388-4e2d-bd72-479265e7d77a.png)
Ta tammmm
New release! Celebration!
![image](https://user-images.githubusercontent.com/564768/196142930-692a2eee-4d31-4f8b-af5f-f3a8d2a08c0b.png) - https://pypi.org/project/icalendar/

**Comment by niccokunzmann** [comment]
A new release v5.0.0 has been made and can be used now.

**Comment by mauritsvanrees** [comment]
Thanks a lot! Wonderful job!
