### ISSUE TITLE
cli fails to write to stdout

### ISSUE THREAD

**Issue by kemlath** [collective/icalendar#435]
icalendar.__version__ = '4.1.0'
python3.8 on ubuntu 20.04

Running "icalendar view file.ics" throws a _TypeError: write() argument must be str, not bytes_ in 

the problem is in main() in cli.py 

`subparser.add_argument(
        '-o', dest='output_handle', metavar='OUTPUT',
        type=argparse.FileType('w'), default=sys.stdout,
        help='output file (default=<stdout>)')
`

this, per default passes `sys.stdout` as `output_handle` in `def view(input_handle, output_handle):` which fails when `bytes` are written to it instead of a `str` during `output_handle.write(_template.format(....).encode('utf-8')`

As long as `argparse.FileType` does not properly recognize binary mode strings (e.g. 'wb') a possible fix would be to default to `sys.stdout.buffer` instead of `sys.stdout`

**Comment by kemlath** [comment]
I'll fork the repo and create a pull request. 
There are a few more issues with the cli that came up since then, I'll fix em all and create a pull request. 

Really the cli should fail all the time under python3 independent on what you write to sys.stdout as long as you encode it to bytes.

**Comment by kemlath** [comment]
I just found out that the version of icalendar I got from pypi is version  '4.1.0' whereas the current master branch is version 5.0x and has a rather different cli.py which no longer has the above described problem. 

Sorry about the confusion

**Comment by niccokunzmann** [comment]
This calls for creating a new release #429.

**Comment by niccokunzmann** [comment]
The new version is released. v5.0.0
