### ISSUE TITLE
Easy Deployments

### ISSUE THREAD

**Issue by niccokunzmann** [collective/icalendar#446]
For my projects, I like it if I create a tag and then this tag gets deployed automatically after all the tests were run.

![image](https://user-images.githubusercontent.com/564768/195097037-5024676f-d601-4ba9-b33b-4d8b860749fc.png)

Here is a successful deployment:
https://github.com/niccokunzmann/python-recurring-ical-events/actions/runs/3227154888/jobs/5281596597

I do like this method because
- it allows for automated testing of the package before deploy
- it speeds up new releases and this makes it easier to integrate new, small changes

The flow would look like this:

1. Anyone with write access follows the [deployment documentation](https://icalendar.readthedocs.io/en/latest/maintenance.html#new-releases) to create a new tag.
2. Maintainers are notified for approval of this tag.
3. If one maintainer approves, the deployment goes to PyPI

@mauritsvanrees Since you run the tests for the Plone community each time before a release, are there requirements that should be taken into account for deployments, more tests to run?

What are your thoughts on this?

Related:
- #429

**Comment by mauritsvanrees** [comment]
It *would* be good if the `plone.app.event` tests would be run against the development version of this package. This is the only package that uses `calendar`. I am making a PR.

**Comment by niccokunzmann** [comment]
This can be closed when
- [ ] #447 is merged
- [ ] #448 is merged
- [ ] action secrets for the `PyPI` environment have been added
- [ ] it is documented that
    - maintainers need to approve the deploy
    - how maintainers are added to the environment
- [ ] a new release has been made and is on PyPI using this method, see #429

**Comment by niccokunzmann** [comment]
This can be closed as all closing criteria are fulfilled.
