### ISSUE TITLE
[BUG] Calendar.from_ical() issue

### ISSUE THREAD

**Issue by vantro** [collective/icalendar#472]
Hello, 
When I try to import an ics file (28Mb) with the following code, the calendar is displayed at the screen without any print() command.

## To Reproduce
```
import icalendar
file="Calendar-2022-10-21-164146"
with open(f'{file}.ics', 'rb') as file:
    ics_text = file.read()
    cal = Calendar.from_ical(ics_text)
```
Output:

```
it's a dump of the file
```

## Environment

 - [x] OS:                               Mac OS Monterey
 - [x] Python version:            Python 3.10 
 - [x] `icalendar` version:      5.0.1

How to browse a large file ?

Thanks

**Comment by jacadzaca** [comment]
Hi, could you attach said calendar? We can't reproduce this atm

**Comment by vantro** [comment]
The ics file can be downloaded here: https://filesender.renater.fr/?s=download&token=c778975e-6fd1-4146-9426-e3db8e8c59d0

**Comment by jacadzaca** [comment]
Grepping the file for `END:VCALENDAR` returns nothing, so the file you've attached is invalid. I appened `END:VCALENDAR` (e.g. `echo 'END:VCALENDAR' >> Calendar-2022-10-21-164146`) to it and it parsed correctly. The dump of the file results from  line 396 of cal.py, where __ repr() __ of a component is appened the error message.

**Comment by jacadzaca** [comment]
For future notice, it's possible to attach files on Github, just drag the file into the comment input box :)

**Comment by niccokunzmann** [comment]
> I appened END:VCALENDAR

That might happen if a file is incomplete.

> The dump of the file results from the line 396 of cal.py, where __ repr() __ of a component is appened the error message.

Hm, maybe it is safe to cut out a few megabytes in `__repr__`.

**Comment by jacadzaca** [comment]
> Hm, maybe it is safe to cut out a few megabytes in `__repr__`.

I created [add_max_error_length](https://github.com/collective/icalendar/compare/master...add_max_error_length) with a test for error message trimming. If everyone likes it, I  can make it green later this week.

**Comment by niccokunzmann** [comment]
That test adds value. I wonder: will people want to see the whole calendar? 100 is a bit more than one line. Will the calendar have the faulty in the message? I think, I would like to check `str` and `repr` and . message.
BUT The most important thing is to solve the issue and have fun and not (my) perfectionism or concerns so much because the fun makes progress: fast releases, people complain, people get involved. Involvement keeps this project alive, vetos and demanding others to comply kill it.

**Comment by jacadzaca** [comment]
I think 100 characters is fine, since more would obfuscate the fact that an exception was thrown (like we see in this issue). Nonetheless, adding a `verbose` argument to the `Calendar.parse_ics` method shouldn't be difficult.

**Comment by vantro** [comment]
as a user, I don't need to see all the events, but reason of the error is enough.
As this file was generated by an application (Zimbra) a notice the bad structure and the missing argument would be fine.

**Comment by niccokunzmann** [comment]
Yes. I would skip the verbose argument as string conversion is property of the exception and not the parsing for me. I am happy with an easy fix.

**Comment by jacadzaca** [comment]
@vantro Since the file was produced by a third party program, you should report the bug to them. Feel free to link this issue to them :)
