### ISSUE TITLE
"icalendar's output is different"?

### ISSUE THREAD

**Issue by ThiefMaster** [collective/icalendar#489]
Sorry, but this clearly wins the least useful changelog entry prize for this year :)

It's listed as a breaking change (so something I should look into when updating this library in my application), but I'm probably not the only one who has absolutely no idea what changed there... Sure, I can generate ical files with the old and new version and compare them, but that's cumbersome...

**Comment by jacadzaca** [comment]
Oh, it's supposed to mean that the output of the [icalendar CLI utility](https://github.com/collective/icalendar/pull/324) has changed.

**Comment by ThiefMaster** [comment]
Ah, so nothing to worry about. Might be useful to mention that in the changelog :)
