### ISSUE TITLE
[BUG] missing \ in replace

### ISSUE THREAD

**Issue by arpitest** [collective/icalendar#525]
here the 3rd replace is bad, it should be \\\\n -> \n:

    elif isinstance(text, bytes):
        return text.replace(b'\\N', b'\\n')\
                   .replace(b'\r\n', b'\n')\
                   .replace(b'\n', b'\n')\
                   .replace(b'\\,', b',')\
                   .replace(b'\\;', b';')\
                   .replace(b'\\\\', b'\\')

**Comment by niccokunzmann** [comment]
Thanks for reporting this! Do you mean
\\n -> \n?
Would you like to work on this?
Could you create a small example snippet that shows the problem? We can convert that to a test.
What are your thoughts on how to proceed?

**Comment by arpitest** [comment]
here is a typo (missing \ ) this does not do anything this way:
.replace(b'\n', b'\n')
compare to non-bytes (str) version...

i dont want to work on this or to write tests etc, just noticed this typo while looking at your implementation and reported it.

**Comment by devdanzin** [comment]
I think this one can be closed.

**Comment by niccokunzmann** [comment]
Thanks!
