### ISSUE TITLE
[BUG] Two `Calendar` objects with different events should not `==` each other

### ISSUE THREAD

**Issue by Lx** [collective/icalendar#526]
## Describe the bug
Given two `Calendar` objects being loaded from a .ics file (one fresh, one cached):

```py
calendar_a: icalendar.cal.Calendar
calendar_b: icalendar.cal.Calendar
```

I would expect (and attempted to rely upon) the `==` operator to reliably test whether they're the same or not (so I can avoid emitting "changes" when no changes have occurred).

`calendar_a == calendar_b` in all cases, regardless of whether their contents differ.

## Expected behavior
The `==` operator correctly returns `True` or `False` depending on content.

**Comment by niccokunzmann** [comment]
Hello Alex, thanks for reporting this. Can you show a bit more code of how you load the calendars? When are they not equal? I did not fully understand how equality is determined. Also: How is this equality universal for all the sub-components?

**Comment by Lx** [comment]
Thanks for looking into this.

- In my use case, an ICS file is periodically downloaded and parsed via `Calendar.from_ical(ics_file_as_bytes)`.
- On subsequent loads, the calendar needs to be compared with the previous one and act only if any event changes have occurred.
  - For avoidance of doubt, two different `Calendar` object instances are being compared—that is, `id(calendar_a) != id(calendar_b)`.
- Most of the time, there is no change, and `calendar_a == calendar_b` has evaluated to `True` (as expected if `Calendar` equality checking has overridden the default mechanism of comparing `id`s).
- When the calendars **do** differ, `calendar_a == calendar_b` still evaluates to `True` (which is very unexpected).

> I did not fully understand how equality is determined.

My expectation would be that `calendar_a == calendar_b` if and only if both calendars convey exactly the same information.  If `calendar_b` had an additional event, or if one of its events' descriptions had been changed, I would expect that `calendar_a != calendar_b`.  I may be misunderstanding your request for clarification—does this help?

> How is this equality universal for all the sub-components?

Sorry, but I don't immediately understand what is being asked.  Could you please rephrase?

Looking broadly at the codebase, it seems that the equality checking is done in `CaselessDict`:

https://github.com/collective/icalendar/blob/b8ff114a275687edeaf6015d51940d1dfe9b2a22/src/icalendar/caselessdict.py#L88-L89

which to me is doubly surprising, because at first glance, this should return `False` whenever two objects' items aren't in the exact same order, let alone if the two objects have a different number of keys.  Could this be a hashing issue maybe?

**Comment by niccokunzmann** [comment]
I am wondering: Could you post two ICS files that evaluate as equal but 
are actually not equal?Message ID: 
***@***.***>

**Comment by yassirasad** [comment]
@niccokunzmann 
This issue occurred to me as well, you can verify it with any two ICS files which are different.

**Comment by niccokunzmann** [comment]
See also #570.
