### ISSUE TITLE
Docs: about.rst needs updating

### ISSUE THREAD

**Issue by deed02392** [collective/icalendar#527]
https://github.com/collective/icalendar/blob/master/docs/about.rst has not been updated for 9 years, and includes a claim that the project hasn't been updated and is therefore outdated. That thankfully doesn't appear to be the case, so it ought to be updated so as to not discourage adoption of the package.

**Comment by niccokunzmann** [comment]
Thanks for reading and reporting this! Would you like to make that change as you would like to see it happen?

**Comment by deed02392** [comment]
I'm not a contributor so I didn't think it'd be appropriate for me to author the about page for the project :-) I don't know enough about the mentioned RFCs or the project to be sure if that part is accurate. Maybe the simplest thing to do is just delete that part and leave the paragraph about Max?

**Comment by niccokunzmann** [comment]
This is your chance to become one :) I had a look. Could you delete the confusing text and create a pull request?

**Comment by bobflorian** [comment]
https://github.com/collective/icalendar/pull/552

**Comment by niccokunzmann** [comment]
#553 closes this.
