### ISSUE TITLE
[BUG] Component._encode ignores parameters if value is native

### ISSUE THREAD

**Issue by Zocker1999NET** [collective/icalendar#557]
## Describe the bug

`Component._encode` ignores the given parameters if the value is already of a native type (see [code in question](https://github.com/collective/icalendar/blob/df769f88694745d3babb87457bc3080965aa62c4/src/icalendar/cal.py#L139-L141)). IMO this is unexpected behavior. This also seems unexpected for the dependent library caldav, where it leads to a RELTYPE to be fully ignored if the passed UID is of type vText (see python-caldav/caldav#334).

## To Reproduce

(I’m not familiar with this library as I only discovered this issue through discovering python-caldav/caldav#334, so the reproducing code is not fully complete.)

```
import icalendar

todo_1  # assume minimal working vTODO
todo_2  # assume other minimal working vTODO

todo_2.add(
    "RELATES-TO",
    todo_1["uid"],
    parameters={"RELTYPE": "DEPENDS-ON"},
)
print(todo_2.to_ical())
```

In the output, the `RELATES-TO` is added, as specified.
However, its missing the parameter `RELTYPE=DEPENDS-ON`.

## Expected behavior

Use the specified parameters (replace or append already existing ones on the native type) or, at least, throw a warning or error that parameter will be ignored.

## Environment

 - [x] OS: Debian GNU/Linux trixie/sid
 - [x] Python version: Python 3.11.5
 - [x] `icalendar` version: 5.0.8

## Additional context

- [x] I tested it with the latest version `pip3 install https://github.com/collective/icalendar.git`
- [x] I attached the ICS source file or there is no ICS source file

**Comment by niccokunzmann** [comment]
Hi, thanks for reporting!

I think the next steps could be writing the code for the TODOs, putting this into a test function, fixing the test.

**Comment by Zocker1999NET** [comment]
Hey, I’m currently writing the tests and I’m unsure with following case:

If a native object with parameters is to be _encoded with further parameters, what would you propose on what should happen:
1. merge old & new parameters
    - would only overwrite in the case of the same property
    - however, can lead to parameters creeping their way to properties where they should not be used
2. overwrite old parameters with new ones
    - potentially removes properties someone wanted to keep

I’m not sure what is the better choice as both seem equally reasonable to me. What’s your opinion on that?

<details>
<summary>Full Example</summary>

Assume following property value with parameters:
```python
val = _encode("X-SOURCE", "SGFsbG8gV2VsdCE=", props={"ENCODING": "BASE64", "LANG": "en", "X-IS-SOURCE": "1"})
```

Following call would happen to `_encode`:
```python
val = _encode("X-TARGET", val, props={"LANG":"de", "X-IS-TARGET": "1"})
```

Both possibilities for the parameters seem reasonable:
1. `{"ENCODING": "BASE64", "LANG": "de", "X-IS-SOURCE": "1", "X-IS-TARGET": "1"}`
    - important `ENCODING` is kept
    - potentially incompatible/unexpected `X-IS-SOURCE` is kept as well
2. `{"LANG": "de", "X-IS-TARGET": "1"}`
    - important `ENCODING` is lost
    - potentially incompatible/unexpected `X-IS-SOURCE` is lost

</details>

**Comment by jacadzaca** [comment]
Hi @Zocker1999NET , for me the first option seems more logical, since `val` stores state and I'd expect _encoding further parameters to imply the keeping of old ones

**Comment by niccokunzmann** [comment]
@jacadzaca would you like to create a new release?

**Comment by jacadzaca** [comment]
@niccokunzmann sure thing :)
