### ISSUE TITLE
OSS-Fuzz Integration

### ISSUE THREAD

**Issue by ennamarie19** [collective/icalendar#562]
My name is McKenna Dallmeyer and I have submitted icalendar to OSS-Fuzz recently. If you are not familiar with the project, OSS-Fuzz is Google's platform for continuous fuzzing of Open Source Software. In order to get the most out of this program, it would be greatly beneficial to be able to merge-in my fuzz harness and build scripts into the upstream repository and contribute bug fixes if they come up. Is this something that you would support me putting the effort into?

**Comment by jacadzaca** [comment]
Hey! Feel free to file a PR(s) and we will happily review it :) If you need some starting point, you might find our single [hypothesis test](https://github.com/collective/icalendar/blob/master/src/icalendar/tests/hypothesis/test_fuzzing.py) helpful.

**Comment by niccokunzmann** [comment]
Yes, a PR sounds nice! How would that be integrated then, I wonder. But, I think that will become clear in the PR.

**Comment by niccokunzmann** [comment]
I would close this as the fuzzer is running.
Linking:
#569  #574 #573 #577
