### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [collective/icalendar#563]
On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by jacadzaca** [comment]
Hi, we could setup a GitHub Releases creation process with minimal additional work, but I think your use-case could be solved more easily by polling icalendar's tag RSS feed. You can find it at this URL: https://github.com/collective/icalendar/tags.atom. I think that this approach would also be much more simple since parsing emails sounds difficult. What do you think?

**Comment by kloczek** [comment]
Thank you ..
As I'm working on Linux/Solaris distribution ..
```console
[tkloczko@pers-jacek SPECS]$ grep VCS:.*https://github.com/ *spec |wc -l; ls -1 *spec|wc -l
3027
4706
```
In other words this is not only about python modules and as you see currently almost 2/3 of all my packages have VCS repos on github and that percentage still is growing.
Processing gh releases notifications allow make async updates.
Processing git tags over gh API is really tricky thing because there are many tagging conventions, sometimes tags are constantly moved (even on daily bases), sometimes what has been tagged should not be uses (in such cases maintainers are not creating on top of such tags gh releases), new tags sometimes are not ascending and .. many, many more reasons (like even refuse by maintainers use git tags .. at all).
Processing gh releases notifications amongst may other possible to use methods bring one of the highest yields (yes .. even that is not perfect and it cannot be only method but still it is one of the best one😞).

**Comment by jacadzaca** [comment]
OK, that makes sense. We'll try to look into creating GitHub releases in near future. You're very welcome to file a PR yourself if you are willing to contribute :)

**Comment by jacadzaca** [comment]
Creating releases should probably take place [here](https://github.com/collective/icalendar/blob/master/.github/workflows/tests.yml#L56)

**Comment by kloczek** [comment]
Really .. thank you very much for understanding 👍 😄 

About PR .. I don't see in gh actions anything which is defines release process.
Nevertheless these links which I've copied contains some examples how to use gh actions/workflows to make release and on release new version over pypi action.
In simples form gh release can be with empty comment however one of those links shows example how to generate automatically changelog included with gh release entry.

**Comment by niccokunzmann** [comment]
@mauritsvanrees, for #564, I would like to create a "fine grained access token" to only create GitHub releases.
The process can only be allowed by organization owners (not me): https://docs.github.com/en/organizations/managing-programmatic-access-to-your-organization/setting-a-personal-access-token-policy-for-your-organization
Can you follow the process to enable fine grained access tokens for "github.com/collective"?

**Comment by mauritsvanrees** [comment]
@niccokunzmann I don't think this works for the current use case: automatically making a GitHub release when a tag is created.  The link you give is about fine grained _personal_ access tokens, and that sounds like something that belongs to one _user_, not one _repo_.

I have created a `RELEASE_TOKEN` secret in the repo.  I don't know if that will work, but may be worth a shot.

If we do want the fine grained personal access tokens, then this would need to be enabled on the full collective, not just icalendar, so I would need to get some more people involved for a second opinion.  I can ping them if the current solution does not work.

BTW, I am release manager for Plone, but I do not have any package where I create release on GitHub.

**Comment by niccokunzmann** [comment]
I would close it once an automated release shows up.

**Comment by mauritsvanrees** [comment]
The weekly gh-actions cronjob failed:

[Invalid workflow file: .github/workflows/tests.yml#L114](https://github.com/collective/icalendar/actions/runs/6522685341/workflow)
The workflow is not valid. .github/workflows/tests.yml (Line: 114, Col: 5): Unexpected value 'deploy-github-release'

A guess: maybe the line with `deploy-github-release` needs to be indented two spaces less.

**Comment by niccokunzmann** [comment]
The current release fails with this error:

```
Run elgohr/Github-Release-Action@v4
Run $GITHUB_ACTION_PATH/entrypoint.sh
/home/runner/work/_actions/elgohr/Github-Release-Action/v4/entrypoint.sh: 2: hub: not found
Error: Process completed with exit code 127.
```
https://github.com/collective/icalendar/actions/runs/6748355950/job/18346549191
