### ISSUE TITLE
This is not an error but I didn't know where else to ask this. Does this lib can open calendars by link?

### ISSUE THREAD

**Issue by thecowmilk** [collective/icalendar#594]
Just the header really but just a demo for what I mean by that. There are some services that say: `copy the link and then import to your calendar.`. Does this lib do it? I didn't see any reference on docs either.

Thanks in Advance!

**Comment by niccokunzmann** [comment]
Hello, this is a good question. What you would do is use another library to open a file by link.
https://stackoverflow.com/questions/15138614/how-can-i-read-the-contents-of-an-url-with-python
The content of that file is what this library uses.

Stackoverflow would be the right place to ask these questions with loads more people answering. I close this and if you have any questions on how to specifically do this, then I would recommend asking it on stackoverflow - you get better answers!
