### ISSUE TITLE
Add examples on complex Event configuration

### ISSUE THREAD

**Issue by bastianwegge** [collective/icalendar#612]
Hello maintainers and icalendar enthusiasts, first of all thank you for this awesome package!
I struggled a little to create a complex event with recurrence and multiple alarms, so that's why I'm basically creating this issue. I haven't found anything related in the documentation, github issues or discussions.

Would a PR be welcome to add examples for complex Events like the one I mentioned? I'd love to bring this in.

**Comment by jacadzaca** [comment]
Hey, we would by honored by such PR :)
