### ISSUE TITLE
Link in Docs Broken

### ISSUE THREAD

**Issue by natashamm** [collective/icalendar#614]
Under https://icalendar.readthedocs.io/en/latest/install.html#running-tests the link  https://tox.wiki/en/latest/example/general.html#selecting-one-or-more-environments-to-run-tests-against to the Tox docs is broken.

**Comment by stevepiercy** [comment]
@natashamm would you please submit a pull request? We'll get it merged. Thank you!

**Comment by niccokunzmann** [comment]
@NP-compete fixed this. Thanks!
