### ISSUE TITLE
Rename branch `master` to `main`

### ISSUE THREAD

**Issue by stevepiercy** [collective/icalendar#627]
Reference: https://github.com/collective/icalendar/pull/623#discussion_r1633086772

**Comment by niccokunzmann** [comment]
- [ ] This also needs adjusting the documentation and the README
- [ ] The test cases should work. 
- [ ] We will see if the changelog tester will pick this up

Github might have a way to rename the branch.

**Comment by stevepiercy** [comment]
> Github might have a way to rename the branch.

Yup.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

**Comment by niccokunzmann** [comment]
This is recommended to update your local clone:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by niccokunzmann** [comment]
I adjusted readthedocs, too.

**Comment by niccokunzmann** [comment]
It seems all conditions for closing this are met. If you witness anything off, please reopen or report in a new issue.
