### ISSUE TITLE
Add documentation pull request preview via Read the Docs

### ISSUE THREAD

**Issue by stevepiercy** [collective/icalendar#669]
Do we have a docs pull request preview, such as that provided by Read the Docs? It would be good to verify that RFC links, API docs, and other markup renders correctly, without pulling down the branch and building the docs locally.

If not, we could copy what I did for [`plone-sphinx-theme`](https://github.com/plone/plone-sphinx-theme/blob/main/.github/workflows/rtd-pr-preview.yml). See also https://github.com/plone/plone-sphinx-theme/blob/main/.readthedocs.yaml#L13-L25 and https://github.com/plone/plone-sphinx-theme/blob/main/Makefile#L215-L217 for complete example.

_Originally posted by @stevepiercy in https://github.com/collective/icalendar/pull/667#discussion_r1660042074_

**Comment by niccokunzmann** [comment]
This sounds good to me!

**Comment by stevepiercy** [comment]
Ref: [Pull request previews](https://docs.readthedocs.io/en/stable/pull-requests.html#pull-request-previews)

**Comment by stevepiercy** [comment]
@niccokunzmann would you please add me as a Maintainer for the RTD project? I am `stevepiercy` on RTD.

https://readthedocs.org/projects/icalendar/

Else please follow the instructions for [How to configure pull request builds](https://docs.readthedocs.io/en/stable/guides/pull-requests.html). Thank you!

**Comment by niccokunzmann** [comment]
> @stevepiercy: Maintainer for the RTD project?

Done!
