### ISSUE TITLE
Add `sphinx-autobuild`

### ISSUE THREAD

**Issue by stevepiercy** [collective/icalendar#673]
When I edit docs, I like when the reload to show how my changes render. I use [`sphinx-autobuild`](https://pypi.org/project/sphinx-autobuild/) for all my documentation.

**Comment by niccokunzmann** [comment]
Hi, this is probably nice. Could you add documentation to https://icalendar.readthedocs.io/en/latest/install.html#building-the-documentation
Then, I would call it a close of the issue. Otherwise, nobody will use this feature.
