### ISSUE TITLE
Test and support Python 3.13

### ISSUE THREAD

**Issue by niccokunzmann** [collective/icalendar#723]
Python 3.13 has been released.

Please

- [x] add the Python version and tests
- [ ] document which files to touch on a Python version change in the docs/maintenance section

**Comment by Firdous2307** [comment]
@niccokunzmann Can I work on this issue, I would love to contribute

**Comment by niccokunzmann** [comment]
@Firdous2307 thanks for asking and yes, please. On this repo, open a PR as soon as you have something and we can feedback and contribute.

**Comment by Firdous2307** [comment]
@niccokunzmann Thanks! I'll open a PR once I have the changes ready for your feedback

**Comment by mreguly** [comment]
hey, I already submitted PR

**Comment by niccokunzmann** [comment]
@mreguly, thanks for doing the changes.

@Firdous2307 I left feedback on #728 for the changelog section and to complete this issue, the documentation would need changing so next time we remove or add a Python version, we know which files to touch. Would you like to do that?

**Comment by Firdous2307** [comment]
@niccokunzmann I had already made all my changes from start and included that part too.

**Comment by Firdous2307** [comment]
@niccokunzmann I have fixed the change logs

**Comment by niccokunzmann** [comment]
@Firdous2307 @mreguly thanks for your work!
