### ISSUE TITLE
Copy documentation from RFC into the components

### ISSUE THREAD

**Issue by niccokunzmann** [collective/icalendar#726]
The RFC motivates the use of a component.

Please copy the motivational text from the [RFC 5545](https://www.rfc-editor.org/info/rfc5545) into the components:

- [ ] Alarm
- [ ] Event
- [ ] Todo
- [ ] FreeBusy
- [ ] Timezone + subclasses
- [ ] Calendar
- [x] Journal - this is done and an example: https://github.com/collective/icalendar/blob/f2c017d3b179783a7c82c954cc331889b4bcbc03/src/icalendar/cal.py#L716

Do not copy too much of the details like specific types and values and such.

**Comment by Firdous2307** [comment]
@niccokunzmann Can I work on this issue, I would love to contribute

**Comment by niccokunzmann** [comment]
@Firdous2307 Yes, please!

**Comment by Firdous2307** [comment]
@niccokunzmann Great!

**Comment by niccokunzmann** [comment]
@Firdous2307 I do not assign issues to contributors. Opening a PR asap is how collaboration speeds up :)

**Comment by Firdous2307** [comment]
@niccokunzmann Alright understood
