### ISSUE TITLE
[BUG] vWeekday does not make `sign`, `weekday` available

### ISSUE THREAD

**Issue by david-venhoff** [collective/icalendar#749]
## Describe the bug

icalendar currently does not make it possible to parse recurrence rules containing something like `BYDAY=-1SU`. To get the frequency of the recurrence from this value, one would have to manually parse `-1SU`. 
That is error prone, and it looks like icalendar [already does this](https://github.com/collective/icalendar/blob/c59966c7d9cdb58b930662870e9f938f83ba7bf4/src/icalendar/prop.py#L928-L931), but then throws away the result

## To Reproduce

- parse an icalendar with a recurrence rule containing `BYDAY=-1SU`
- See that there is no way to access `sign` and `weekday` in the resulting `vWeekday`. `relative` is made available, however without its sign.

## Expected behavior

`vWeekday` should make these data public

## Environment

 - [x] OS:                               os independent
 - [x] Python version:            python independent
 - [x] `icalendar` version: 6.1.0

**Comment by niccokunzmann** [comment]
Thanks for reporting this! I estimate this to be a small change to fix. Could you create a pull request with a test for this?

**Comment by david-venhoff** [comment]
Yes, I can do that :)
