### ISSUE TITLE
Add rrule from a string

### ISSUE THREAD

**Issue by fluxxcode** [collective/icalendar#758]
We have a rrule string that we want to add to an event.

At the moment this doesn't seem possible because the semicolons in the rrule strings are escaped with a backslash, invalidating the rrule.

Here is an example:
```python
import icalendar

rrule_str = "FREQ=YEARLY;INTERVAL=10;BYMONTH=12"

event = Event()

# Both result in the same output
event.add("rrule", rrule_str)
event["rrule"] = rrule_str
```

Calling `.to_ical` escapes the rrule: `RRULE:FREQ=YEARLY\;INTERVAL=10\;BYMONTH=12`, making it invalid.

I think something like `event.add_unescaped` would be helpful.

**Comment by niccokunzmann** [comment]
Hi, thanks! It should somehow be possible to do that.

I would look for something like this:

```python
from icalendar import vRecur

event["rrule"] = vRecur.from_ical("FREQ=YEARLY;INTERVAL=10;BYMONTH=12")
```

If you find a working example, could you add it to the documentation?
https://icalendar.readthedocs.io/en/latest/api.html#icalendar.prop.vRecur

**Comment by fluxxcode** [comment]
Thank you for the answer!

```python
event["rrule"] = vRecur.from_ical("FREQ=YEARLY;INTERVAL=10;BYMONTH=12")
````

works perfectly. Will create a PR for an example in the documentation.
